# Ce fichier porte les paramètres helm spécifiques à kubernetes
imagePullSecrets:
  - name: registry-credentials
dockerRegistry: 192.168.1.248
app:
  replicas: 2
  requests:
    cpu: "0.1"
    memory: "64Mi"
  limits:
    cpu: "0.2"
    memory: "128Mi"
service:
  type: "ClusterIP"