apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/gohlink/branche-unique-scenarios.git
      revision: main
      directories:
      - path: apps/*/envs/prod ## <=== Déploiera seulement les apps possédant un répertoire envs/prod
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}' 
    spec:
      project: default

      source:
        repoURL: https://github.com/gohlink/branche-unique-scenarios.git
        targetRevision: main
        path: '{{.path.path}}' ## <=== Pointe vers le répertoire envs/prod de chaque application trouvée par le générateur

        ## Can also be set as configmap if we want to apply server-wide
        # kustomize:
        #   buildOptions: --enable-helm

      destination:
        server: https://kubernetes.default.svc
        namespace: default # '{{index .path.segments 1}}-{{index .path.segments 3}}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      