# Ce fichier porte les paramètres helm spécifiques à kubernetes
imagePullSecrets:
  - name: registry-credentials
app:
  replicas: 3
  requests:
    cpu: "0.2"
    memory: "128Mi"
  limits:
    cpu: "0.4"
    memory: "256Mi"
service:
  type: "NodePort"
  nodePort: "30003"